import {
  ROSCO_ALPHABET,
  answerMatchesLetterRule,
  defaultMatchTypeForLetter,
  type LetterClue,
  type Rosco,
} from '@rosco/shared';

function buildRosco(
  id: string,
  title: string,
  difficulty: Rosco['difficulty'],
  theme: string,
  entries: [clue: string, answer: string][],
): Rosco {
  if (entries.length !== ROSCO_ALPHABET.length) {
    throw new Error(
      `Rosco "${id}" debe tener ${ROSCO_ALPHABET.length} pistas, tiene ${entries.length}`,
    );
  }
  const letters: LetterClue[] = ROSCO_ALPHABET.map((letter, i) => {
    const [clue, answer] = entries[i];
    const matchType = defaultMatchTypeForLetter(letter);
    if (!answerMatchesLetterRule(answer, letter, matchType)) {
      throw new Error(
        `Rosco "${id}": la respuesta "${answer}" no cumple la regla de la letra "${letter}" (${matchType})`,
      );
    }
    return { letter, clue, answer, matchType };
  });
  return { id, title, difficulty, theme, letters, source: 'preset' };
}

export const PRESET_ROSCOS: Rosco[] = [
  buildRosco('general-facil', 'Cultura general (fácil)', 'facil', 'general', [
    ['Planta de gran tamaño con tronco, ramas y hojas, como el roble o el pino.', 'árbol'],
    ['Vehículo de dos ruedas que se mueve pedaleando.', 'bicicleta'],
    ['Vivienda donde vive una familia.', 'casa'],
    ['Cada una de las cinco partes en que termina la mano.', 'dedo'],
    ['Edificio donde los niños van a aprender.', 'escuela'],
    ['Órgano de las plantas, normalmente coloreado y con aroma.', 'flor'],
    ['Felino doméstico que maúlla.', 'gato'],
    ['Lo pone la gallina y se puede freír o cocer.', 'huevo'],
    ['Construcción religiosa donde se reza, con campanario.', 'iglesia'],
    ['Lugar con plantas y flores, normalmente en una casa.', 'jardín'],
    ['Astro que ilumina la noche.', 'luna'],
    ['Mueble con cuatro patas donde se come.', 'mesa'],
    ['Fruto seco pequeño y duro, protegido por una cáscara.', 'nuez'],
    ['Periodo de tiempo de 365 días.', 'año'],
    ['Parte del cuerpo con la que se oye.', 'oreja'],
    ['Ave grande de la Antártida que no vuela.', 'pingüino'],
    ['Producto lácteo derivado de la leche cuajada.', 'queso'],
    ['Animal roedor pequeño, típico compañero del gato en las fábulas.', 'ratón'],
    ['Astro que da luz y calor a la Tierra de día.', 'sol'],
    ['Bebida caliente hecha con hojas, muy popular en Inglaterra.', 'té'],
    ['Fruta pequeña y redonda, morada o verde, con la que se hace vino.', 'uva'],
    ['Animal doméstico que da leche y dice "muu".', 'vaca'],
    ['Instrumento musical de percusión con láminas de madera que se golpean con baquetas.', 'xilófono'],
    ['Alimento lácteo fermentado y cremoso que se toma de postre o desayuno.', 'yogur'],
    ['Calzado que se pone en los pies para caminar.', 'zapato'],
  ]),

  buildRosco('animales-facil', 'Animales (fácil)', 'facil', 'animales', [
    ['Ave rapaz de gran tamaño, símbolo de fuerza y libertad.', 'águila'],
    ['Mamífero marino gigante, el animal más grande del planeta.', 'ballena'],
    ['Mamífero del desierto con una o dos jorobas.', 'camello'],
    ['Mamífero marino muy inteligente que salta fuera del agua y se comunica con clics.', 'delfín'],
    ['Mamífero de gran tamaño con trompa y colmillos de marfil.', 'elefante'],
    ['Ave de plumaje rosado que suele estar de pie sobre una sola pata.', 'flamenco'],
    ['Ave doméstica de corral; el macho tiene cresta roja y canta al amanecer.', 'gallo'],
    ['Insecto muy trabajador que vive en colonias y carga alimentos varias veces su peso.', 'hormiga'],
    ['Reptil de gran tamaño, verde, típico de zonas tropicales, con cresta en el lomo.', 'iguana'],
    ['Felino salvaje con manchas, el más grande de América.', 'jaguar'],
    ['Rey de la selva, felino con una gran melena en los machos.', 'león'],
    ['Primate inteligente y ágil que trepa árboles y come plátanos.', 'mono'],
    ['Mamífero semiacuático de pelaje denso que juega con piedras sobre su pecho.', 'nutria'],
    ['Mamífero andino de lana muy fina y apreciada, parecido a la llama.', 'vicuña'],
    ['Mamífero grande y peludo que hiberna en invierno; le gusta la miel.', 'oso'],
    ['Ave marina blanca y negra que no vuela y vive en la Antártida.', 'pingüino'],
    ['Ave de vistoso plumaje verde y rojo, símbolo de Guatemala.', 'quetzal'],
    ['Anfibio verde que salta y croa, vive cerca del agua.', 'rana'],
    ['Reptil sin patas que repta por el suelo y puede ser venenoso.', 'serpiente'],
    ['Felino más grande del mundo, de rayas negras y naranjas.', 'tigre'],
    ['Ave de plumaje blanco y negro, muy lista, conocida por robar objetos brillantes.', 'urraca'],
    ['Animal doméstico que da leche y dice "muu".', 'vaca'],
    ['Raza de perro robusto y musculoso, de hocico chato, usada antiguamente en peleas.', 'bóxer'],
    ['Bóvido de pelo largo que vive en el Himalaya y se usa como animal de carga.', 'yak'],
    ['Mamífero de hocico puntiagudo y cola larga y peluda, astuto por naturaleza.', 'zorro'],
  ]),

  buildRosco('cine-medio', 'Cine y series (medio)', 'medio', 'cine', [
    ['Película de James Cameron ambientada en el planeta Pandora, protagonizada por los Na\'vi.', 'Avatar'],
    ['Superhéroe de Gotham City que se disfraza de murciélago para luchar contra el crimen.', 'Batman'],
    ['Película en blanco y negro de 1942 ambientada en Marruecos, con la frase "Siempre nos quedará París".', 'Casablanca'],
    ['Célebre personaje vampiro creado por Bram Stoker, adaptado muchas veces al cine.', 'Drácula'],
    ['Película de Disney ambientada en Colombia sobre una familia con dones mágicos.', 'Encanto'],
    ['Película de Disney sobre dos hermanas, una de las cuales congela todo lo que toca.', 'Frozen'],
    ['Película protagonizada por Russell Crowe sobre un general romano convertido en esclavo y gladiador.', 'Gladiator'],
    ['Joven mago protagonista de una saga de libros y películas que estudia en Hogwarts.', 'Harry Potter'],
    ['Película de Christopher Nolan sobre un viaje a través de un agujero de gusano para salvar a la humanidad.', 'Interstellar'],
    ['Película sobre un juego de mesa mágico que cobra vida y transporta a los jugadores a la selva.', 'Jumanji'],
    ['Musical protagonizado por Emma Stone y Ryan Gosling ambientado en Los Ángeles.', 'La La Land'],
    ['Película de ciencia ficción en la que Neo descubre que la realidad es una simulación.', 'Matrix'],
    ['Pez payaso protagonista de una película de Pixar que se pierde en el océano.', 'Nemo'],
    ['Palabra que indica el periodo de estreno de una película, como "2023".', 'año'],
    ['Estatuilla dorada que se entrega en los premios más importantes del cine de Hollywood.', 'Oscar'],
    ['Saga de películas sobre bucaneros del Caribe protagonizada por Johnny Depp.', 'Piratas del Caribe'],
    ['Personaje de James Bond que le proporciona los gadgets y armas especiales.', 'Q'],
    ['Película sobre un boxeador de Filadelfia interpretado por Sylvester Stallone.', 'Rocky'],
    ['Película de animación sobre un ogro verde que vive en un pantano.', 'Shrek'],
    ['Película de James Cameron sobre el hundimiento de un transatlántico en 1912.', 'Titanic'],
    ['Película de Pixar sobre un anciano que ata miles de globos a su casa para viajar.', 'Up'],
    ['Grupo de superhéroes de Marvel formado por Iron Man, Thor, Hulk y Capitán América.', 'Vengadores'],
    ['Grupo de mutantes superhéroes liderados por el Profesor Xavier.', 'X-Men'],
    ['Maestro Jedi de orejas puntiagudas y gran sabiduría de la saga Star Wars.', 'Yoda'],
    ['Película de animación de Disney sobre una coneja policía en una ciudad de mamíferos.', 'Zootrópolis'],
  ]),

  buildRosco('geografia-medio', 'Geografía (medio)', 'medio', 'geografia', [
    ['Continente donde se encuentran países como Egipto, Kenia y Sudáfrica.', 'África'],
    ['País de Sudamérica famoso por el fútbol, el Amazonas y el carnaval de Río.', 'Brasil'],
    ['País alargado de Sudamérica, entre la cordillera de los Andes y el océano Pacífico.', 'Chile'],
    ['País escandinavo cuya capital es Copenhague.', 'Dinamarca'],
    ['País europeo de la península ibérica cuya capital es Madrid.', 'España'],
    ['País europeo cuya capital es París, famoso por la Torre Eiffel.', 'Francia'],
    ['País europeo cuna de la civilización occidental, con capital en Atenas.', 'Grecia'],
    ['País centroamericano cuya capital es Tegucigalpa.', 'Honduras'],
    ['País europeo con forma de bota, cuya capital es Roma.', 'Italia'],
    ['País asiático formado por un archipiélago, cuya capital es Tokio.', 'Japón'],
    ['País africano fundado por esclavos liberados de Estados Unidos, cuya capital es Monrovia.', 'Liberia'],
    ['País norteamericano al sur de Estados Unidos, cuya capital es Ciudad de México.', 'México'],
    ['País europeo de fiordos y auroras boreales, cuya capital es Oslo.', 'Noruega'],
    ['Desfiladero profundo excavado por un río entre montañas, como el "Gran ..." del Colorado.', 'cañón'],
    ['Extensión de agua salada más grande que un mar, como el Pacífico o el Atlántico.', 'océano'],
    ['País sudamericano con Machu Picchu y la ciudad de Lima como capital.', 'Perú'],
    ['Capital de Ecuador, situada en los Andes.', 'Quito'],
    ['País europeo, el más grande del mundo, cuya capital es Moscú.', 'Rusia'],
    ['País europeo de los Alpes, famoso por sus relojes, el chocolate y su neutralidad.', 'Suiza'],
    ['País del sudeste asiático conocido como "la tierra de las sonrisas", cuya capital es Bangkok.', 'Tailandia'],
    ['País sudamericano entre Argentina y Brasil, cuya capital es Montevideo.', 'Uruguay'],
    ['País asiático en forma de "S", cuya capital es Hanói.', 'Vietnam'],
    ['Estado del sur de México famoso por su gastronomía, el mezcal y sus ruinas de Monte Albán.', 'Oaxaca'],
    ['Península mexicana donde se encuentran las ruinas mayas de Chichén Itzá.', 'Yucatán'],
    ['País africano cuya capital es Harare, antes llamado Rodesia.', 'Zimbabue'],
  ]),

  buildRosco('ciencia-dificil', 'Ciencia (difícil)', 'dificil', 'ciencia', [
    ['Unidad básica de la materia, formada por protones, neutrones y electrones.', 'átomo'],
    ['Rama de la ciencia que estudia los seres vivos.', 'biología'],
    ['Unidad estructural y funcional básica de todos los seres vivos.', 'célula'],
    ['Magnitud física que relaciona la masa de un cuerpo con su volumen.', 'densidad'],
    ['Forma de energía generada por el movimiento de electrones a través de un conductor.', 'electricidad'],
    ['Proceso mediante el cual las plantas producen su alimento usando luz solar, agua y CO2.', 'fotosíntesis'],
    ['Fuerza que atrae los cuerpos hacia el centro de la Tierra, descrita por Newton.', 'gravedad'],
    ['Elemento químico más ligero y abundante del universo, símbolo H.', 'hidrógeno'],
    ['Átomo o partícula que ha perdido o ganado electrones, con carga eléctrica.', 'ion'],
    ['Instrumento de laboratorio con tubo y émbolo usado para inyectar o extraer líquidos.', 'jeringa'],
    ['Estado de la materia con volumen definido pero forma variable, como el agua a temperatura ambiente.', 'líquido'],
    ['Cambio irreversible en la secuencia del ADN que puede originar nuevas características.', 'mutación'],
    ['Partícula subatómica sin carga eléctrica que forma parte del núcleo atómico junto a los protones.', 'neutrón'],
    ['Unidad astronómica que mide la distancia que recorre la luz en 365 días.', 'año luz'],
    ['Gas presente en el aire, imprescindible para la respiración, de símbolo O2.', 'oxígeno'],
    ['Partícula subatómica con carga positiva que se encuentra en el núcleo del átomo.', 'protón'],
    ['Rama de la ciencia que estudia la composición, propiedades y transformación de la materia.', 'química'],
    ['Proceso por el cual los seres vivos convierten el oxígeno en energía liberando CO2.', 'respiración'],
    ['Estado de la materia con forma y volumen definidos, como el hielo.', 'sólido'],
    ['Magnitud física que mide el grado de calor de un cuerpo, se mide en grados.', 'temperatura'],
    ['Conjunto de todo lo que existe: galaxias, estrellas, planetas y materia.', 'universo'],
    ['Preparado biológico que genera inmunidad frente a una enfermedad.', 'vacuna'],
    ['Tipo de radiación electromagnética usada para ver el interior del cuerpo humano, como en una radiografía.', 'rayos X'],
    ['Elemento químico no metálico usado como antiséptico y esencial para la tiroides.', 'yodo'],
    ['Célula resultante de la unión del óvulo y el espermatozoide, primera etapa de un nuevo ser vivo.', 'zigoto'],
  ]),

  buildRosco('historia-dificil', 'Historia (difícil)', 'dificil', 'historia', [
    ['Civilización precolombina que habitó México, constructora de pirámides, célebre por su calendario.', 'azteca'],
    ['Adjetivo que designa al Imperio de Oriente que perduró tras la caída de Roma, con capital en Constantinopla.', 'bizantino'],
    ['Movimientos militares religiosos medievales organizados por los cristianos para recuperar Jerusalén.', 'cruzadas'],
    ['Periodo de gobierno de un solo líder con poder absoluto, como el de Franco en España.', 'dictadura'],
    ['Periodo de la historia europea entre la caída del Imperio Romano y el Renacimiento.', 'Edad Media'],
    ['Sistema social y económico medieval basado en la relación entre señores y vasallos.', 'feudalismo'],
    ['Enfrentamiento armado entre países o bandos; la Segunda ... Mundial ocurrió entre 1939 y 1945.', 'guerra'],
    ['Ciencia que estudia los hechos del pasado de la humanidad.', 'historia'],
    ['Territorio gobernado por un emperador, formado por la unión de varios pueblos bajo un mismo poder.', 'imperio'],
    ['Heroína francesa que luchó contra los ingleses en la Guerra de los Cien Años y fue quemada en la hoguera.', 'Juana de Arco'],
    ['Unidad básica del ejército romano, formada por miles de soldados.', 'legión'],
    ['Forma de gobierno en la que el poder recae en un rey o una reina.', 'monarquía'],
    ['Periodo final de la Edad de Piedra, caracterizado por la agricultura, la ganadería y la piedra pulida.', 'neolítico'],
    ['Palabra que designa cada periodo de 365 días usado para datar los hechos históricos, como el "1492".', 'año'],
    ['Forma de gobierno en la que el poder está en manos de un pequeño grupo de personas.', 'oligarquía'],
    ['Época anterior a la aparición de la escritura, dividida en Paleolítico y Neolítico.', 'prehistoria'],
    ['Dios azteca representado como una serpiente emplumada.', 'Quetzalcóatl'],
    ['Movimiento cultural y artístico que floreció en Europa entre los siglos XIV y XVI, tras la Edad Media.', 'Renacimiento'],
    ['Periodo de cien años usado para ordenar la historia, como el "XV", en el que Colón llegó a América.', 'siglo'],
    ['Faraón egipcio niño cuya tumba, casi intacta, fue hallada en 1922 por Howard Carter.', 'Tutankamón'],
    ['Antiguo país comunista formado tras la Revolución Rusa de 1917 y disuelto en 1991.', 'Unión Soviética'],
    ['Pueblo navegante escandinavo que realizó incursiones y conquistas por Europa entre los siglos VIII y XI.', 'vikingos'],
    ['Cifra romana que representa el número 10 y aparece en nombres de reyes como Luis ...', 'X'],
    ['Instrumento de madera que se coloca sobre el cuello de los bueyes para tirar del arado.', 'yugo'],
    ['Movimiento revolucionario indígena surgido en Chiapas (México) en 1994, también apodo de un guerrero mexicano encapuchado.', 'zapatista'],
  ]),

  buildRosco('deportes-dificil', 'Deportes (difícil)', 'dificil', 'deportes', [
    ['Deporte de pista con vallas, saltos y lanzamientos; incluye pruebas como los 100 metros lisos.', 'atletismo'],
    ['Deporte de equipo en el que se encesta un balón en un aro elevado.', 'baloncesto'],
    ['Deporte que se practica sobre una bicicleta, como el Tour de Francia.', 'ciclismo'],
    ['Acción de avanzar botando el balón sin perder su control, típica del baloncesto y el fútbol.', 'dribbling'],
    ['Deporte de combate con espadas en el que hay que tocar al rival sin ser tocado.', 'esgrima'],
    ['Deporte de equipo más popular del mundo; se juega con los pies y un balón buscando marcar goles.', 'fútbol'],
    ['Deporte en el que se golpea una pequeña bola con palos intentando meterla en hoyos.', 'golf'],
    ['Deporte de equipo sobre hielo que se juega con un disco (puck) y bastones.', 'hockey'],
    ['En judo, puntuación máxima que se otorga por una técnica perfecta y gana el combate al instante.', 'ippon'],
    ['Deporte de combate de origen japonés en el que se busca derribar al rival usando su propia fuerza.', 'judo'],
    ['Prueba de atletismo en la que se arroja lo más lejos posible un disco de metal.', 'lanzamiento de disco'],
    ['Carrera de atletismo de 42,195 kilómetros de distancia.', 'maratón'],
    ['Deporte que se practica en el agua desplazándose mediante el movimiento de brazos y piernas.', 'natación'],
    ['Cada uno de los periodos de 365 días que separan una edición de los Juegos Olímpicos de la siguiente.', 'año'],
    ['Competición deportiva internacional que se celebra cada cuatro años, reuniendo a atletas de todo el mundo.', 'Olimpiadas'],
    ['Deporte de raqueta que se juega en una pista dividida por una red, similar al tenis pero con pala.', 'pádel'],
    ['Posición del fútbol americano encargada de organizar el ataque y lanzar el balón a sus compañeros.', 'quarterback'],
    ['Deporte de equipo de origen inglés que se juega con un balón ovalado que se puede llevar con las manos.', 'rugby'],
    ['Deporte de tabla que se practica sobre las olas del mar.', 'surf'],
    ['Deporte de raqueta con pelota amarilla que se juega en una pista dividida por una red.', 'tenis'],
    ['Atuendo idéntico que visten los deportistas de un mismo equipo.', 'uniforme'],
    ['Deporte de equipo en el que se golpea un balón con las manos por encima de una red sin que toque el suelo.', 'voleibol'],
    ['Nombre genérico de los deportes de riesgo y adrenalina, como el skate o el BMX: deportes ...', 'extremos'],
    ['Nombre españolizado del jinete profesional que monta caballos de carreras.', 'yóquey'],
    ['Acción de lanzarse de cabeza o de pie al agua, fundamental en la natación y los clavados.', 'zambullida'],
  ]),

  buildRosco('cultura-general-dificil', 'Cultura general avanzada (difícil)', 'dificil', 'cultura general', [
    ['Conjunto de letras que sirven para representar por escrito los sonidos de un idioma.', 'alfabeto'],
    ['Edificio o sala donde se guardan y prestan libros.', 'biblioteca'],
    ['Instrumento óptico formado por lentes usado para tomar fotografías.', 'cámara'],
    ['Libro que recoge, por orden alfabético, el significado de las palabras de un idioma.', 'diccionario'],
    ['Obra de arte tridimensional realizada tallando, modelando o fundiendo un material como la piedra o el bronce.', 'escultura'],
    ['Ciencia que estudia la naturaleza, la materia, la energía y sus interacciones.', 'física'],
    ['Ciencia que estudia la forma y el relieve de la superficie terrestre.', 'geografía'],
    ['Composición musical solemne que representa a un país o una institución.', 'himno'],
    ['Sistema de comunicación propio de una comunidad, como el español o el inglés.', 'idioma'],
    ['Persona encargada de dictar sentencia en un juicio en un tribunal.', 'juez'],
    ['Arte de combinar palabras con un fin estético; incluye la poesía, la novela y el teatro.', 'literatura'],
    ['Edificio donde se exponen y conservan obras de arte u objetos de interés histórico y científico.', 'museo'],
    ['Relato de ficción, escrito en prosa, con personajes y una trama.', 'novela'],
    ['Proceso creativo de planificar la forma, función y estética de un objeto antes de fabricarlo.', 'diseño'],
    ['Conjunto de músicos que interpretan una obra con instrumentos de cuerda, viento y percusión.', 'orquesta'],
    ['Composición literaria en verso que expresa sentimientos mediante el uso del lenguaje y el ritmo.', 'poesía'],
    ['Sustancia formada por la combinación de dos o más elementos; también, la ciencia que la estudia.', 'química'],
    ['Medio de comunicación que transmite sonido a través de ondas, sin imagen.', 'radio'],
    ['Composición musical extensa para orquesta, dividida generalmente en varios movimientos.', 'sinfonía'],
    ['Obra literaria escrita para ser representada por actores ante un público, dividida en actos.', 'teatro'],
    ['Institución de enseñanza superior donde se cursan carreras y se obtienen títulos.', 'universidad'],
    ['Cada línea de un poema, con métrica y a veces rima.', 'verso'],
    ['Instrumento de percusión formado por láminas de madera de distinto tamaño que se golpean con baquetas.', 'xilófono'],
    ['Material blanco en polvo que, mezclado con agua, se usa en escultura, construcción y para inmovilizar huesos rotos.', 'yeso'],
    ['Género lírico español que combina partes cantadas y habladas, muy popular en el siglo XIX.', 'zarzuela'],
  ]),
];

export function getPresetById(id: string): Rosco | undefined {
  return PRESET_ROSCOS.find((r) => r.id === id);
}
